name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests in virtual environment
        run: |
          echo "Activating virtualenv..."
          source ~/Desktop/pycharm_projects/Re-ProtGNN/protgnn_env/bin/activate
          
          echo "Checking Python version and location:"
          which python
          python -V

          echo "Verifying torch installation:"
          python -c "import torch; print('Torch version:', torch.__version__); print('CUDA available:', torch.cuda.is_available())"

          echo "Running tests with PYTHONPATH=./src"
          export PYTHONPATH=./src
          pytest test/
